Repository beyond-sw-camp/be10-2nd-1DANDOIT-mat.zip, pull requests merged in 2024-10, with the labels that each got.

#3 fix: RequestMapping 오타 수정
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/BoardQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostCmtQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ListLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostCmtLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/PostLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/query/controller/LikeController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListBoxCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCollectCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/MatzipCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/MatzipQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/PenaltyCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostCmtController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/command/application/controller/RestaurantCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/restaurant/query/controller/RestaurantQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/application/controller/ReviewCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/sercurity/config/SecurityConfig.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/controller/UsersAuthController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/ActiveLevelQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersActivityQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersFollowQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersQueryController.java
Labels: fix

#5 feat: 쪽지 보내기 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/controller/MessageController.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/dto/SendMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/service/MessageService.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/repository/MessageDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/service/MessageDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/infrastructure/repository/MessageInfraRepository.java
Labels: fix, feat

#6 fix: FeignClient쪽 GetMapping 오타 수정
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/UserFeignClient.java
Labels: fix

#9 feat: 리뷰 좋아요 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/controller/ReviewLikeController.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/dto/ReviewLikeDTO.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/application/service/ReviewLikeService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/repository/ReviewLikeRepository.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/domain/service/ReviewLikeDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/like/command/infrastructure/repository/ReviewLikeInfraRepository.java
Labels: feat

#11 feat: 쪽지방 목록 조회 구현
  matzipback/src/main/java/com/matzip/matzipback/message/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageShortDTO.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/service/MessageQueryService.java
  matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml
Labels: feat

#14 feat: 쪽지방 상세 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/message/query/controller/MessageQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageDetailDTO.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/mapper/MessageMapper.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/service/MessageQueryService.java
  matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml
Labels: feat

#16 feat: 쪽지 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/controller/MessageController.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/application/service/MessageService.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/aggregate/Messages.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/repository/MessageDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/message/command/domain/service/MessageDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/message/query/dto/MessageDetailDTO.java
  matzipback/src/main/resources/mappers/MessageMappers/MessageMapper.xml
Labels: refactoring, feat

#18 feat: 패널티 검색 및 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/PenaltyCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/PenaltyQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/PenaltyDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/dto/PenaltyListResponse.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/PenaltyMapper.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/service/PenaltyQueryService.java
  matzipback/src/main/resources/mappers/reportMappers/PenaltyMapper.xml
Labels: feat

#13 feat: #12 리스트 댓글 조회 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListCommentQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListCommentSearchDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListCommentQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListCommentQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListCommentQueryMapper.xml
Labels: feat

#20 feat: 회원 활동 등급 수정, 삭제 (관리자 기능)
  matzipuser/src/main/java/com/matzip/matzipuser/exception/ErrorCode.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/controller/ActiveLevelController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/controller/EmailController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/dto/UpdateActiveLevelDTO.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/application/service/ActiveLevelService.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/domain/repository/UserActiveLevelRepository.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/domain/service/ActiveLevelDomainService.java
Labels: refactoring, feat

#22 feat: 게시판 카테고리 등록 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/dto/BoardCategoryRequest.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/BoardCategory.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/BoardCategoryRepository.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/infrastructure/repository/BoardCategoryInfraRepository.java
Labels: feat

#23 feat: 1차 리뷰 신고 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReviewReportController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/dto/ReportMappingDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/dto/ReportReasonDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReviewReportService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/ReportReason.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReportReasonDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ReviewReportRequest.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ReportReasonRepository.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewRepository.java
Labels: fix, feat

#25 chore: #23 리스트 상세조회 기능 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListContentDTO.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: chore

#28 Chore: 본인 리스트박스 조회 기능 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListBoxListDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchAllDTO.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: chore

#29 feat: 게시판 카테고리 수정 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/aggregate/BoardCategory.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/BoardCategoryRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/PenaltyQueryController.java
Labels: feat

#33 feat: 게시판 카테고리 삭제 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/BoardCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/BoardCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/domain/repository/BoardCategoryRepository.java
Labels: feat

#35 refactoring: 신고 기능 통합 및 정리
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportListController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostCmtController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReportPostController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/dto/ReportMappingDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/dto/ReportRequest.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/PenaltyCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportListService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostCmtService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReportPostService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/aggregate/Report.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ListDomainRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ListDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/service/ReportDomainService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListCmtReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListCmtReportReqMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/ListReportReqMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PostReportResMessageDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/dto/PtAndCmtReportReqDTO.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/infrastructure/repository/ListInfraRepository.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/ReportMapper.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/service/ReportQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/repository/ReviewRepository.java
  matzipback/src/main/resources/mappers/reportMappers/ReportMapper.xml
Labels: fix, refactoring

#37 Chore: 다른 유저 리스트 박스 조회 -> 페이징처리 #36
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListBoxResponse.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: chore

#41 chore: #40 본인 리스트 조회 페이징 처리
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
Labels: chore

#44 feat: #43 리스트 전체 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListAllResponse.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: feat, chore

#46 feat: #45 인기리스트 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/mapper/ListQueryMapper.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/service/ListQueryService.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: feat

#51 chore: 게시글, 게시글 댓글 조회 시 응답에 userSeq 추가
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostCommentDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDTO.java
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: chore

#53 fix: #52 리스트 댓글 삭제 본인만 가능하게 컨트롤러 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCmtCommandController.java
Labels: fix

#55 fix: #54 리스트 삭제 본인만 가능하게 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
Labels: fix

#57 fix: #56 리스트 수정 본인만 가능하게 변경
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/UpdateListRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/domain/service/DomainListUpdateService.java
Labels: fix

#59 fix: #58 리스트 삭제 본인만 가능하게 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/controller/ListCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/dto/DeleteListRequest.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/command/application/service/ListCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
Labels: fix, chore

#61 refactoring: 회원 활동포인트 업데이트 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/service/PostCommandService.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/domain/aggregate/UserActivity.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/command/domain/service/UserActivityDomainService.java
Labels: refactoring

#66 feat: 로그인 시도 시 정지, 탈퇴 여부 검증
  matzipuser/src/main/java/com/matzip/matzipuser/security/config/SecurityConfig.java
  matzipuser/src/main/java/com/matzip/matzipuser/security/handler/LoginSuccessHandler.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/dto/userInfo/UserStatusDTO.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/mapper/UsersInfoMapper.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/service/UsersInfoService.java
  matzipuser/src/main/resources/mappers/usersMappers/UserListMapper.xml
Labels: feat

#64 feat: 게시글 에디터 기능 구현
  matzipback/build.gradle
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/config/WebMvcConfig.java
Labels: feat

#68 feat: Top10 인기태그 조회 기능 구현
  matzipback/src/main/java/com/matzip/matzipback/board/query/controller/PostQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/mapper/PostMapper.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/service/PostQueryService.java
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: feat

#72 chore: url 변경
  matzipback/src/main/java/com/matzip/matzipback/sercurity/util/UserFeignClient.java
  matzipuser/src/main/java/com/matzip/matzipuser/security/config/SecurityConfig.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersQueryController.java
Labels: chore

#76 chore: 간단한 수정
  matzipuser/src/main/java/com/matzip/matzipuser/security/config/SecurityConfig.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersQueryController.java
  matzipuser/src/main/resources/mappers/usersMappers/UserListMapper.xml
Labels: chore

#78 feat: activeLevel 페이징 처리를 위한 기능 구현
  matzipuser/src/main/java/com/matzip/matzipuser/security/config/SecurityConfig.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/ActiveLevelQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/service/ActiveLevelQueryService.java
Labels: feat

#81 fix : #80 ListQueryMapper.xml 쿼리문 수정
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: fix

#82 refactor: 에디터 사용을 위한 리팩토링
  matzipback/src/main/java/com/matzip/matzipback/board/command/application/controller/PostCommandController.java
  matzipback/src/main/java/com/matzip/matzipback/config/WebMvcConfig.java
Labels: refactoring

#84 refactor: 게시글 조회 기능을 위한 쿼리 수정
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/BoardCategoryDTO.java
  matzipback/src/main/java/com/matzip/matzipback/board/query/dto/PostDTO.java
  matzipback/src/main/resources/mappers/boardMappers/BoardMapper.xml
  matzipback/src/main/resources/mappers/boardMappers/PostMapper.xml
Labels: refactoring

#86 fix: 시큐리티 버그 수정
  matzipuser/src/main/java/com/matzip/matzipuser/security/config/SecurityConfig.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/controller/UsersQueryController.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/mapper/UsersInfoMapper.java
  matzipuser/src/main/java/com/matzip/matzipuser/users/query/service/UsersInfoService.java
  matzipuser/src/main/resources/mappers/usersMappers/UserListMapper.xml
Labels: fix

#87 feat: 자잘한 기능 추가
  matzipback/src/main/java/com/matzip/matzipback/report/query/controller/ReportQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/mapper/ReportMapper.java
  matzipback/src/main/java/com/matzip/matzipback/report/query/service/ReportQueryService.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/controller/ReviewQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/mapper/ReviewMapper.java
  matzipback/src/main/java/com/matzip/matzipback/review/query/service/ReviewQueryService.java
  matzipback/src/main/resources/mappers/ReviewMappers/ReviewMapper.xml
  matzipback/src/main/resources/mappers/reportMappers/ReportMapper.xml
Labels: feat, chore

#91 fix: 시큐리티 문제로 공통 권한 설정 추가
  matzipuser/src/main/java/com/matzip/matzipuser/security/config/SecurityConfig.java
Labels: fix

#93 fix: listSeq 누락 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/controller/ListQueryController.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchAllDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchDTO.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: fix, chore

#95 fix: #94 DTO 수정
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/ListSearchAllDTO.java
Labels: fix, chore

#96 fix: 리스트 맛집 상세 조회 시 음식점 시퀀스 추가
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/MatzipDTO.java
  matzipback/src/main/java/com/matzip/matzipback/matzipList/query/dto/MatzipSearchDTO.java
  matzipback/src/main/resources/mappers/listMappers/ListQueryMapper.xml
Labels: fix

#97 fix: 신고 사유 삭제 메서드 수정
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/controller/ReasonController.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/application/service/ReasonCommandService.java
  matzipback/src/main/java/com/matzip/matzipback/report/command/domain/repository/ReasonsRepository.java
Labels: fix

#98 fix: 불의의 사고로 변경된 리뷰 테이블명 수정
  matzipback/src/main/java/com/matzip/matzipback/review/command/domain/aggregate/Review.java
Labels: fix
